name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Build
        run: mkdir build && cd build && cmake .. && make
      - name: Run tests
        run: cd build && ctest --output-on-failure

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang tools
        run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy

      - name: Run clang-format (check only)
        run: |
          find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -n --Werror

      - name: Run clang-tidy
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cd ..
          clang-tidy $(find src include -name '*.cpp') -- -Iinclude
